name: Publish Website

on:
  push:
    branches:
      - trunk
  workflow_dispatch:
jobs:
  Publish-Website:
    name: Publish-Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'blocks/categories-section/package-lock.json'
      - run: npm install --prefix blocks/categories-section
      - run: npm run build --prefix blocks/categories-section
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpcom
          path: |
            .
            !.git*
            !node_modules
            !package-lock.json
            !package.json